# Generated by Django 4.1.3 on 2023-05-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faxr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='image/')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='image/')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('about', models.CharField(max_length=999)),
            ],
        ),
    ]
