# Generated by Django 4.1.3 on 2023-05-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0002_faxr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutt', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Faxrr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='image/')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='image/')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('about', models.CharField(max_length=999)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap.author')),
            ],
        ),
        migrations.DeleteModel(
            name='Faxr',
        ),
    ]
