# Generated by Django 4.1.3 on 2023-05-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0003_author_faxrr_delete_faxr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faxr1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='image/')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='image/')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('about', models.CharField(max_length=999)),
                ('aboutt', models.CharField(max_length=999)),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='aboutt',
            new_name='about1',
        ),
        migrations.DeleteModel(
            name='Faxrr',
        ),
        migrations.AddField(
            model_name='faxr1',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap.author'),
        ),
    ]
