# Generated by Django 4.1.3 on 2023-05-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0005_authorr_maktab'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maktab',
            new_name='Uqituvchi',
        ),
    ]
