# Generated by Django 4.1.3 on 2023-05-20 13:38

import ap.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0006_rename_maktab_uqituvchi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Darslik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.CharField(max_length=150)),
                ('video', models.FileField(upload_to='video/%y', validators=[ap.validators.file_size])),
                ('theme', models.CharField(max_length=999)),
            ],
        ),
    ]
