# Generated by Django 4.1.3 on 2023-05-20 14:53

import ap.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0008_uqituvchii_delete_darslik_delete_uqituvchi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Udars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan', models.CharField(max_length=150)),
                ('video', models.FileField(upload_to='video/%y', validators=[ap.validators.file_size])),
                ('theme', models.CharField(max_length=999)),
            ],
        ),
        migrations.RemoveField(
            model_name='uqituvchii',
            name='fan',
        ),
        migrations.RemoveField(
            model_name='uqituvchii',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='uqituvchii',
            name='video',
        ),
        migrations.AlterField(
            model_name='aloqa',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='faxr1',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uqituvchii',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
