# Generated by Django 4.1.3 on 2023-05-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0010_uqituv_delete_udars_delete_uqituvchii'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image/')),
                ('about', models.CharField(max_length=999)),
                ('joy', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
