# Generated by Django 4.1.3 on 2023-05-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0011_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='image/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(upload_to='image/')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('about', models.CharField(max_length=999)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
