# Generated by Django 4.1.3 on 2023-05-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0012_aboutt_delete_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutt',
            name='name',
        ),
        migrations.AddField(
            model_name='aboutt',
            name='joy',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
