# Generated by Django 4.1.3 on 2023-05-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0014_remove_aboutt_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aboutt',
            new_name='About',
        ),
    ]
