# Generated by Django 4.1.3 on 2023-05-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0015_rename_aboutt_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='image/')),
                ('ism', models.CharField(blank=True, max_length=100)),
                ('img', models.ImageField(upload_to='image/')),
                ('about', models.CharField(max_length=999)),
            ],
        ),
    ]
