# Generated by Django 4.1.3 on 2023-05-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0016_direktor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Direktor',
            new_name='Zamdirektor',
        ),
    ]
