# Generated by Django 4.1.3 on 2023-05-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0017_rename_direktor_zamdirektor'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamdirektor',
            name='rasm',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
