# Generated by Django 4.1.3 on 2023-05-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0018_zamdirektor_rasm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zamdirektor',
            new_name='Direktor',
        ),
    ]
