# Generated by Django 4.1.3 on 2023-05-22 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0020_remove_direktor_rasm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faxrimiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='image/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(upload_to='image/')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('about', models.CharField(max_length=999)),
                ('aboutt', models.CharField(max_length=999)),
                ('rasm', models.ImageField(upload_to='image/')),
                ('rasm2', models.ImageField(upload_to='image/')),
                ('rasm3', models.ImageField(upload_to='image/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap.author')),
            ],
        ),
        migrations.DeleteModel(
            name='Faxr1',
        ),
    ]
