# Generated by Django 4.1.3 on 2023-05-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0021_faxrimiz_delete_faxr1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faxrimiz',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='faxrimiz',
            name='rasm2',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='faxrimiz',
            name='rasm3',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
